services:
  web:
    image: susindusaksew/student-attendance-system:latest
    container_name: student-attendance
    ports:
      - "5000:5000"
    volumes:
      - attendance_data:/app/data

volumes:
  attendance_data: